/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 angelwing.gltf 
Author: DemiGod1410 (https://sketchfab.com/DemiGod1410)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/anglewing-7e60f49b0de346e1b5cb7a7ac7264c38
Title: AngleWing
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/angelwing.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={0.004}>
        <mesh 
          geometry={nodes.AngleWing_Texture_0.geometry} 
          material={materials.Texture} 
          position={[0, 0, 0]} 
          rotation={[ -3, -3, 0]} 
          scale={[102.044, 102.045, 108.172]} 
        />
      </group>
    </group>
  )
}

useGLTF.preload('/angelwing.gltf')
