/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Jupiter.gltf 
*/

import React from 'react'
import { useGLTF, PerspectiveCamera } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/Jupiter.gltf')
  return (
    <group {...props} dispose={null}>
      <PerspectiveCamera makeDefault={false} far={1000} near={0.1} fov={22.895} position={[-10.276, 8.435, -7.41]} rotation={[0.257, 0.375, -0.721]} scale={2.983} />
      <mesh geometry={nodes.Jupiter.geometry} material={materials.Jupiter_texture} position={[-12.399, 13.955, -32.215]} rotation={[2.586, 1.416, -2.555]} scale={11.645} />
    </group>
  )
}

useGLTF.preload('/Jupiter.gltf')
